name: CD to Staging

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x gradlew
      - run: ./gradlew build test jacocoTestReport

      - name: SonarCloud Scan
        if: github.event_name == 'push'
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: build/libs/*.jar

  deploy:
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gatherlove-auth.jar
          path: build/libs/

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: |
          echo "web: java -jar build/libs/gatherlove_auth.jar" > Procfile
          zip deploy.zip build/libs/gatherlove-auth.jar Procfile

      - run: |
          VERSION="deploy-$(date +%s)"
          aws s3 cp deploy.zip "s3://${{ secrets.AWS_S3_BUCKET }}/$VERSION.zip"
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "$VERSION" \
            --source-bundle "S3Bucket=${{ secrets.AWS_S3_BUCKET }},S3Key=$VERSION.zip"
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_STAGING_ENV }}" \
            --version-label "$VERSION"